#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

NODES_FILE=${NODES_FILE:-configs/nodes/agent_env_tau2_train_3x8.txt}
ENV_POOL_SIZE=${ENV_POOL_SIZE:-64}
ENV_PORT=${ENV_PORT:-18182}
ROUTER_PORT=${ROUTER_PORT:-19082}
RAY_CUDA_VISIBLE_DEVICES=${RAY_CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
NUM_GPUS_PER_NODE_FOR_RAY=${NUM_GPUS_PER_NODE_FOR_RAY:-8}

MODEL_BASENAME=${MODEL_BASENAME:-Qwen3.5-4B}
MODEL_ARGS_SCRIPT=${MODEL_ARGS_SCRIPT:-scripts/models/qwen3.5-4B.sh}
EXP_PROJECT=${EXP_PROJECT:-${PROJECT_NAME:-${MODEL_BASENAME}_tau2_grpo}}
EXP_NAME=${EXP_NAME:-${RUN_NAME:-tau2-areal-${MODEL_BASENAME}-grpo-3train-1aux-pool64-gbs128-rb16-n8-tp4-cp2-mtpgpu16384-logpchunk1024}}
RUN_ROOT=${RUN_ROOT:-/mnt/bn/jixf-nas-lq/mlf/runs/${EXP_PROJECT}/${EXP_NAME}}
LOG_DIR=${LOG_DIR:-${RUN_ROOT}/logs}
WANDB_DIR=${WANDB_DIR:-${RUN_ROOT}/wandb}
SAVE_DIR=${SAVE_DIR:-${RUN_ROOT}/checkpoints}
WANDB_PROJECT=${WANDB_PROJECT:-${EXP_PROJECT}}
WANDB_ENTITY=${WANDB_ENTITY:-yilgrimage-bytedance}
WANDB_GROUP=${WANDB_GROUP:-${EXP_NAME}}

TOTAL_NUM_STEPS=${TOTAL_NUM_STEPS:-100}
SAVE_INTERVAL=${SAVE_INTERVAL:-${TOTAL_NUM_STEPS}}
RESUME_FROM=${RESUME_FROM:-}
SEED=${SEED:-42}
ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-16}
N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-8}
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-128}
ROLLOUT_MAX_CONTEXT_LEN=${ROLLOUT_MAX_CONTEXT_LEN:-32768}
ROLLOUT_MAX_RESPONSE_LEN=${ROLLOUT_MAX_RESPONSE_LEN:-8192}
MAX_TOKENS_PER_GPU=${MAX_TOKENS_PER_GPU:-16384}
LOG_PROBS_CHUNK_SIZE=${LOG_PROBS_CHUNK_SIZE:-1024}
SGLANG_SERVER_CONCURRENCY=${SGLANG_SERVER_CONCURRENCY:-16}
ACTOR_NUM_NODES=${ACTOR_NUM_NODES:-1}
ACTOR_GPUS=${ACTOR_GPUS:-8}
ROLLOUT_GPUS=${ROLLOUT_GPUS:-16}
NUM_GPUS=${NUM_GPUS:-8}
TP_SIZE=${TP_SIZE:-4}
CP_SIZE=${CP_SIZE:-2}
USE_KL_LOSS=${USE_KL_LOSS:-0}
KL_LOSS_COEF=${KL_LOSS_COEF:-0.00}
FORCE_PROMPT_DATA=${FORCE_PROMPT_DATA:-1}
LOSS_MASK_TYPE=${LOSS_MASK_TYPE:-qwen3_5}
ROLLOUT_CASE_DUMP_N=${ROLLOUT_CASE_DUMP_N:-4}
ROLLOUT_CASE_DUMP_TRACE=${ROLLOUT_CASE_DUMP_TRACE:-both}

EXTRA_LAUNCH_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) EXTRA_LAUNCH_ARGS+=(--dry-run); shift ;;
    -h|--help) echo "Usage: $(basename "$0") [--dry-run]"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

export RAY_CUDA_VISIBLE_DEVICES NUM_GPUS_PER_NODE_FOR_RAY LOG_DIR

LOAD_ARGS=()
if [ -n "${RESUME_FROM}" ]; then
  LOAD_ARGS=(LOAD_DIR="${RESUME_FROM}")
fi

TRAIN_CMD=$(
  printf '%q ' \
    MLF_NAS_ROOT=/mnt/bn/jixf-nas-lq/mlf MLF_LOCAL_ROOT=/tmp/mlf-runtime MLF_LOCAL_ENVS=/tmp/mlf-envs \
    MODEL_BASENAME="${MODEL_BASENAME}" MODEL_ARGS_SCRIPT="${MODEL_ARGS_SCRIPT}" \
    SLIME_ENV=/tmp/mlf-envs/slime CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" RAY_CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" \
    NUM_GPUS="${NUM_GPUS}" EXP_PROJECT="${EXP_PROJECT}" EXP_NAME="${EXP_NAME}" RUN_ROOT="${RUN_ROOT}" LOG_DIR="${LOG_DIR}" WANDB_DIR="${WANDB_DIR}" SAVE_DIR="${SAVE_DIR}" ${LOAD_ARGS[@]+"${LOAD_ARGS[@]}"} \
    USE_EXISTING_AGENT_INFRA=1 SUBMIT_VIA_RAY_JOB=1 ENABLE_WANDB=1 WANDB_PROJECT="${WANDB_PROJECT}" WANDB_ENTITY="${WANDB_ENTITY}" WANDB_GROUP="${WANDB_GROUP}" TRAIN_ENTRYPOINT=train_async.py \
    NUM_STEPS="${TOTAL_NUM_STEPS}" NUM_ROLLOUT="${TOTAL_NUM_STEPS}" SAVE_INTERVAL="${SAVE_INTERVAL}" ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE}" N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT}" GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
    ROLLOUT_MAX_CONTEXT_LEN="${ROLLOUT_MAX_CONTEXT_LEN}" ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN}" MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU}" LOG_PROBS_CHUNK_SIZE="${LOG_PROBS_CHUNK_SIZE}" SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY}" LOSS_MASK_TYPE="${LOSS_MASK_TYPE}" \
    ACTOR_NUM_NODES="${ACTOR_NUM_NODES}" ACTOR_GPUS="${ACTOR_GPUS}" ROLLOUT_GPUS="${ROLLOUT_GPUS}" TP_SIZE="${TP_SIZE}" CP_SIZE="${CP_SIZE}" SEED="${SEED}" USE_KL_LOSS="${USE_KL_LOSS}" KL_LOSS_COEF="${KL_LOSS_COEF}" FORCE_PROMPT_DATA="${FORCE_PROMPT_DATA}" \
    AGENT_ENV_ROLLOUT_DUMP_N="${ROLLOUT_CASE_DUMP_N}" AGENT_ENV_ROLLOUT_DUMP_TRACE="${ROLLOUT_CASE_DUMP_TRACE}" \
    bash examples/agent_env/tau2/scripts/run_tau2_grpo.sh
)

cd "${REPO_DIR}"
bash scripts/mlf/launch_agentic_training.sh \
  --env tau2 \
  --nodes "${NODES_FILE}" \
  --env-pool-size "${ENV_POOL_SIZE}" \
  --env-port "${ENV_PORT}" \
  --router-port "${ROUTER_PORT}" \
  --train-cmd "${TRAIN_CMD}" \
  ${EXTRA_LAUNCH_ARGS+"${EXTRA_LAUNCH_ARGS[@]}"}
