#!/usr/bin/env bash
set -euo pipefail

MLF_NAS_ROOT=${MLF_NAS_ROOT:-/mnt/bn/jixf-nas-lq/mlf}
REPO_DIR=${REPO_DIR:-${MLF_NAS_ROOT}/code/slime}
MLF_LOCAL_ENVS=${MLF_LOCAL_ENVS:-/tmp/mlf-envs}
MLF_LOCAL_ROOT=${MLF_LOCAL_ROOT:-/tmp/mlf-runtime}
WANDB_SECRET_FILE=${WANDB_SECRET_FILE:-${MLF_NAS_ROOT}/secrets/wandb.env}

RUN_PROFILE=${RUN_PROFILE:-}
INTERNAL_ROLE=
RESOLVED_CONFIG=
DRY_RUN=0

ENV_NAME=${ENV_NAME:-}
ENV_CONFIG=${ENV_CONFIG:-}
MODEL_PROFILE=${MODEL_PROFILE:-}
TRAIN_PROFILE=${TRAIN_PROFILE:-}
TRAIN_ADAPTER=${TRAIN_ADAPTER:-examples/agent_env/scripts/run_agent_env_train.sh}
TOPOLOGY_PROFILE=${TOPOLOGY_PROFILE:-}
AUX_PROFILE=${AUX_PROFILE:-}

NODES_FILE=${NODES_FILE:-}
AUX_NODES_FILE=${AUX_NODES_FILE:-}
NODE_INDICES=${NODE_INDICES:-}
AUX_NODE_INDICES=${AUX_NODE_INDICES:-}
ENV_PORT=${ENV_PORT:-}
ROUTER_PORT=${ROUTER_PORT:-}
RAY_PORT=${RAY_PORT:-6379}
RAY_CUDA_VISIBLE_DEVICES=${RAY_CUDA_VISIBLE_DEVICES:-}
NUM_GPUS_PER_NODE_FOR_RAY=${NUM_GPUS_PER_NODE_FOR_RAY:-}
RAY_MIN_WORKER_PORT=${RAY_MIN_WORKER_PORT:-}
RAY_MAX_WORKER_PORT=${RAY_MAX_WORKER_PORT:-}
RAY_START_MAX_ATTEMPTS=${RAY_START_MAX_ATTEMPTS:-2}
RAY_HEAD_START_TIMEOUT_S=${RAY_HEAD_START_TIMEOUT_S:-90}

EXP_PROJECT=${EXP_PROJECT:-}
EXP_NAME=${EXP_NAME:-}
RUN_ROOT=${RUN_ROOT:-}
LOG_DIR=${LOG_DIR:-}
WANDB_DIR=${WANDB_DIR:-}
SAVE_DIR=${SAVE_DIR:-}

RESET_TRAIN_RUNTIME_ON_START=${RESET_TRAIN_RUNTIME_ON_START:-1}
BENCH_ON_TRAIN_EXIT=${BENCH_ON_TRAIN_EXIT:-1}
BENCH_ON_LAUNCH_FAILURE=${BENCH_ON_LAUNCH_FAILURE:-1}
BENCH_ON_EXIT_SUPPRESS_FILE=${BENCH_ON_EXIT_SUPPRESS_FILE:-/tmp/mlf_suppress_bench_on_train_exit_until}

SSH_USER=${SSH_USER:-tiger}
SSH_PORT=${SSH_PORT:-10413}
if [ -z "${SSH_KEY:-}" ]; then
  if [ -f "${MLF_NAS_ROOT}/secrets/byte_id_rsa" ]; then
    SSH_KEY="${MLF_NAS_ROOT}/secrets/byte_id_rsa"
  else
    SSH_KEY="/home/${SSH_USER}/.ssh/byte_id_rsa"
  fi
fi
SSH_KEY=${SSH_KEY/#\~/${HOME}}
SSH_IPV6=${SSH_IPV6:-1}
SSH_JUMP=${SSH_JUMP:-}

SLIME_ENV=${SLIME_ENV:-${MLF_LOCAL_ENVS}/slime}
SLIME_PYTHON=${SLIME_PYTHON:-${SLIME_ENV}/bin/python}

usage() {
  cat <<'EOF'
Usage:
  launch_agentic_training.sh <run-profile.env> [--dry-run]

Internal roles:
  launch_agentic_training.sh --internal-role head --resolved RUN_ROOT/logs/resolved_launch.env
  launch_agentic_training.sh --internal-role worker --resolved RUN_ROOT/logs/resolved_launch.env --head-address HOST

The public entrypoint loads run/topology/model/train/aux profiles once, writes
resolved env files under RUN_ROOT/logs, starts aux if configured, resets/stops
train-node runtime, then submits one head tmux. The head/worker roles consume
only the resolved launch env and do not re-parse profiles.
EOF
}

if [ $# -gt 0 ] && [[ "${1}" != -* ]]; then
  RUN_PROFILE=$1
  shift
fi

HEAD_ADDRESS=${HEAD_ADDRESS:-}
while [ $# -gt 0 ]; do
  case "$1" in
    --internal-role) INTERNAL_ROLE=$2; shift 2 ;;
    --resolved) RESOLVED_CONFIG=$2; shift 2 ;;
    --head-address) HEAD_ADDRESS=$2; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

configure_internal_no_proxy() {
  local additions existing host_ips
  additions="localhost,127.0.0.1,0.0.0.0,::1"
  if [ -n "${HEAD_ADDRESS:-}" ]; then
    additions="${additions},${HEAD_ADDRESS}"
  fi
  host_ips="$(hostname -I 2>/dev/null | tr ' ' ',' | sed 's/,$//' || true)"
  if [ -n "${host_ips}" ]; then
    additions="${additions},${host_ips}"
  fi
  existing="${no_proxy:-${NO_PROXY:-}}"
  if [ -n "${existing}" ]; then
    export no_proxy="${additions},${existing}"
  else
    export no_proxy="${additions}"
  fi
  export NO_PROXY="${no_proxy}"
}

configure_internal_no_proxy

resolve_path() {
  local path=${1:-}
  [ -n "${path}" ] || return 0
  if [[ "${path}" = /* ]]; then
    printf '%s\n' "${path}"
  else
    printf '%s/%s\n' "${REPO_DIR}" "${path}"
  fi
}

bool_true() {
  case "${1:-0}" in
    1|true|TRUE|yes|YES|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

quote_exports() {
  local key
  for key in "$@"; do
    printf '%s=%q\n' "${key}" "${!key-}"
  done
}

source_env_file() {
  local path=$1
  local label=${2:-profile}
  path=$(resolve_path "${path}")
  [ -f "${path}" ] || { echo "Missing ${label}: ${path}" >&2; exit 1; }
  set -a
  # shellcheck disable=SC1090
  source "${path}"
  set +a
}

profile_keys() {
  local path
  for path in "$@"; do
    [ -n "${path}" ] || continue
    path=$(resolve_path "${path}")
    [ -f "${path}" ] || continue
    sed -nE 's/^([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "${path}"
  done
}

write_resolved_profile() {
  local target=$1
  shift
  local profile_paths=("$@")
  shift $#
  mkdir -p "$(dirname "${target}")"
  {
    printf '# Generated by %s\n' "$(basename "$0")"
    profile_keys "${profile_paths[@]}" | awk 'NF && !seen[$0]++' | while read -r key; do
      printf '%s=%q\n' "${key}" "${!key-}"
    done
  } > "${target}"
}

write_named_env() {
  local target=$1
  shift
  mkdir -p "$(dirname "${target}")"
  {
    printf '# Generated by %s\n' "$(basename "$0")"
    quote_exports "$@"
  } > "${target}"
}

read_nodes_from() {
  local nodes_file=${1:-}
  local selector=${2:-}
  if [ -z "${nodes_file}" ]; then
    echo "this"
  elif [ -z "${selector}" ]; then
    awk 'NF && $1 !~ /^#/ {print $1}' "${nodes_file}"
  else
    awk -v sel="${selector}" '
      BEGIN {
        n = split(sel, parts, ",")
        for (i = 1; i <= n; i++) wanted[parts[i]] = 1
        idx = 0
      }
      NF && $1 !~ /^#/ {
        if (idx in wanted) print $1
        idx++
      }
    ' "${nodes_file}"
  fi
}

read_nodes() {
  read_nodes_from "${NODES_FILE}" "${NODE_INDICES}"
}

first_node() {
  read_nodes | head -n 1
}

node_count() {
  read_nodes | wc -l | tr -d ' '
}

is_current_node() {
  local node=$1
  [ "${node}" = "this" ] && return 0
  [ "${node}" = "$(hostname)" ] && return 0
  hostname -I 2>/dev/null | tr ' ' '\n' | grep -qx "${node}" && return 0
  ip addr 2>/dev/null | grep -Fq "${node}" && return 0
  return 1
}

http_host() {
  local node=$1
  if [[ "${node}" == *:* ]]; then
    printf '[%s]' "${node}"
  else
    printf '%s' "${node}"
  fi
}

safe_label() {
  local value=$1
  value=${value//:/_}
  value=${value//./_}
  value=${value//\//_}
  printf '%s\n' "${value}"
}

local_node_label() {
  local ip
  ip=$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -m1 . || true)
  safe_label "${ip:-$(hostname)}"
}

role_log_path() {
  local name=$1
  local stem=${name%.*}
  local ext=
  [ "${stem}" = "${name}" ] || ext=".${name##*.}"
  if [ "${INTERNAL_ROLE:-}" = "worker" ]; then
    printf '%s/%s_%s%s\n' "${LOG_DIR}" "${stem}" "$(local_node_label)" "${ext}"
  else
    printf '%s/%s\n' "${LOG_DIR}" "${name}"
  fi
}

ssh_node() {
  local host=$1
  local remote_cmd=$2
  local encoded wrapped
  local args=()
  [ "${SSH_IPV6}" = "1" ] && args+=("-6")
  args+=(
    "-n"
    "-o" "BatchMode=yes"
    "-o" "StrictHostKeyChecking=no"
    "-o" "UserKnownHostsFile=/dev/null"
    "-o" "GlobalKnownHostsFile=/dev/null"
    "-o" "CheckHostIP=no"
    "-o" "IdentitiesOnly=yes"
    "-i" "${SSH_KEY}"
    "-p" "${SSH_PORT}"
  )
  [ -z "${SSH_JUMP}" ] || args+=("-J" "${SSH_JUMP}")
  args+=("${SSH_USER}@${host}")
  encoded=$(printf '%s' "${remote_cmd}" | base64 | tr -d '\n')
  wrapped=$(printf "printf %%s '%s' | base64 -d | bash" "${encoded}")
  if [ "${DRY_RUN}" = "1" ]; then
    printf '+ ssh %s %q\n' "${host}" "${remote_cmd}"
    return 0
  fi
  ssh "${args[@]}" "${wrapped}"
}

remote_query() {
  local host=$1
  local cmd=$2
  local attempt
  for attempt in 1 2 3; do
    if ssh_node "${host}" "${cmd}"; then
      return 0
    fi
    echo "Retry ${attempt}/3 failed on ${host}" >&2
    sleep 5
  done
  return 1
}

remote_first_ip() {
  local host=$1
  remote_query "${host}" "hostname -I | tr ' ' '\n' | grep -m1 ."
}

tmux_start_local() {
  local session=$1
  local script=$2
  local log=${3:-}
  if [ "${DRY_RUN}" = "1" ]; then
    echo "+ tmux ${session}"
    printf '%s\n' "${script}"
    return 0
  fi
  tmux kill-session -t "${session}" 2>/dev/null || true
  local tmp="/tmp/${session}.sh"
  printf '%s\n' "${script}" > "${tmp}"
  chmod +x "${tmp}"
  if [ -n "${log}" ]; then
    mkdir -p "$(dirname "${log}")"
    tmux new-session -d -s "${session}" "bash ${tmp} > ${log} 2>&1"
  else
    tmux new-session -d -s "${session}" "bash ${tmp}"
  fi
}

tmux_start_remote() {
  local host=$1
  local session=$2
  local script=$3
  local log=${4:-}
  local payload remote_cmd
  payload=$(printf '%s\n' "${script}" | base64 | tr -d '\n')
  remote_cmd=$(cat <<EOF
set -euo pipefail
tmp=/tmp/${session}.sh
printf %s '${payload}' | base64 -d > "\${tmp}"
chmod +x "\${tmp}"
tmux kill-session -t ${session@Q} 2>/dev/null || true
EOF
)
  if [ -n "${log}" ]; then
    remote_cmd+=$(printf '\nmkdir -p %q\ntmux new-session -d -s %q "bash %q > %q 2>&1"\n' "$(dirname "${log}")" "${session}" "/tmp/${session}.sh" "${log}")
  else
    remote_cmd+=$(printf '\ntmux new-session -d -s %q "bash %q"\n' "${session}" "/tmp/${session}.sh")
  fi
  echo "Starting ${session} on ${host}"
  remote_query "${host}" "${remote_cmd}"
}

tmux_session_active() {
  local session=$1
  tmux has-session -t "${session}" 2>/dev/null
}

run_bench_nodes() {
  local action=$1
  local nodes_file=$2
  local selector=${3:-}
  [ -n "${nodes_file}" ] || return 0
  local cmd
  cmd=$(printf 'MLF_NAS_ROOT=%q SSH_KEY=%q SSH_IPV6=%q bash %q %q --nodes %q' \
    "${MLF_NAS_ROOT}" "${SSH_KEY}" "${SSH_IPV6}" "${MLF_NAS_ROOT}/bash/run_bench.sh" "${action}" "${nodes_file}")
  [ -z "${selector}" ] || cmd+=$(printf ' --node %q' "${selector}")
  if [ "${DRY_RUN}" = "1" ]; then
    echo "+ ${cmd}"
  else
    bash -lc "${cmd}" || true
  fi
}

reset_runtime_cmd() {
  local suppress_until
  suppress_until=$(( $(date +%s) + 180 ))
  cat <<EOF
set +e
if [ -n "${BENCH_ON_EXIT_SUPPRESS_FILE}" ]; then
  mkdir -p "$(dirname "${BENCH_ON_EXIT_SUPPRESS_FILE}")" 2>/dev/null || true
  printf '%s\n' "${suppress_until}" > "${BENCH_ON_EXIT_SUPPRESS_FILE}" 2>/dev/null || true
fi
for session in mlf_ray_head mlf_ray_worker mlf_${ENV_NAME}_env mlf_${ENV_NAME}_router mlf_${ENV_NAME}_train mlf_multi_head mlf_multi_worker; do
  tmux kill-session -t "\${session}" 2>/dev/null || true
done
if [ -x "${SLIME_PYTHON}" ]; then
  "${SLIME_PYTHON}" -m ray.scripts.scripts stop --force >/tmp/mlf_ray_stop.log 2>&1 || true
elif command -v ray >/dev/null 2>&1; then
  ray stop --force >/tmp/mlf_ray_stop.log 2>&1 || true
fi
pkill -f '[s]glang.launch_server' 2>/dev/null || true
pkill -f '[s]lime/ray/train' 2>/dev/null || true
pkill -f '[t]rain_async.py' 2>/dev/null || true
pkill -f '[t]rain_async_compat.py' 2>/dev/null || true
pkill -f '[r]un_agent_env_train.sh' 2>/dev/null || true
pkill -f '[e]xamples/agent_env/.*/server.py' 2>/dev/null || true
pkill -f '[e]xamples/agent_env/router.py' 2>/dev/null || true
pkill -f '[r]aylet|[g]cs_server|[p]lasma_store|[d]ashboard_agent|[d]ashboard.py' 2>/dev/null || true
EOF
}

reset_runtime_on_nodes() {
  [ "${RESET_TRAIN_RUNTIME_ON_START}" = "1" ] || return 0
  local node cmd
  cmd=$(reset_runtime_cmd)
  for node in $(read_nodes); do
    echo "Resetting training runtime on ${node}"
    if is_current_node "${node}"; then
      [ "${DRY_RUN}" = "1" ] && echo "+ local reset" || bash -lc "${cmd}" || true
    else
      ssh_node "${node}" "${cmd}" || true
    fi
  done
}

require_runtime() {
  [ "${DRY_RUN}" = "1" ] && return 0
  [ -x "${SLIME_PYTHON}" ] || { echo "Missing slime python: ${SLIME_PYTHON}" >&2; exit 1; }
  case "${ENV_NAME}" in
    webshop) [ -x "${MLF_LOCAL_ENVS}/webshop/bin/python" ] || { echo "Missing WebShop env" >&2; exit 1; } ;;
    alfworld) [ -x "${MLF_LOCAL_ENVS}/alfworld/bin/python" ] || { echo "Missing ALFWorld env" >&2; exit 1; } ;;
    tau2) [ -x "${MLF_LOCAL_ENVS}/tau2/bin/python" ] || { echo "Missing tau2 env" >&2; exit 1; } ;;
    appworld) [ -x "${MLF_LOCAL_ENVS}/appworld/bin/python" ] || { echo "Missing AppWorld env" >&2; exit 1; } ;;
    *) echo "Unsupported env: ${ENV_NAME}" >&2; exit 1 ;;
  esac
}

load_aux_endpoint_env() {
  [ -n "${AUX_ENV_FILE:-}" ] || return 0
  [ -f "${AUX_ENV_FILE}" ] || return 0
  [ "${DRY_RUN:-0}" = "0" ] || return 0
  # shellcheck disable=SC1090
  source "${AUX_ENV_FILE}"
}

server_runtime_exports() {
  printf 'export MLF_NAS_ROOT=%q\n' "${MLF_NAS_ROOT}"
  printf 'export MLF_LOCAL_ROOT=%q\n' "${MLF_LOCAL_ROOT}"
  printf 'export MLF_LOCAL_ENVS=%q\n' "${MLF_LOCAL_ENVS}"
  printf 'export REPO_DIR=%q\n' "${REPO_DIR}"
  printf 'export WEBSHOP_DATA=%q\n' "${MLF_LOCAL_ROOT}/data/webshop"
  printf 'export ALFWORLD_DATA=%q\n' "${MLF_LOCAL_ROOT}/data/alfworld"
  printf 'export ALFWORLD_LIB=%q\n' "${MLF_NAS_ROOT}/code/alfworld"
  printf 'export APPWORLD_ROOT=%q\n' "${MLF_LOCAL_ROOT}/data/appworld"
  printf 'export TAU2_DATA_DIR=%q\n' "${MLF_LOCAL_ROOT}/data/tau2/data"
  printf 'export AUX_ENDPOINT_PROVIDER=%q\n' "${AUX_ENDPOINT_PROVIDER:-}"
  printf 'export AUX_ENDPOINT_MODEL=%q\n' "${AUX_ENDPOINT_MODEL:-}"
  printf 'export AUX_ENDPOINT_BASE_URL=%q\n' "${AUX_ENDPOINT_BASE_URL:-}"
  printf 'export AUX_ENDPOINT_API_KEY_PATH=%q\n' "${AUX_ENDPOINT_API_KEY_PATH:-}"
  printf 'export AUX_ENDPOINT_TIMEOUT_S=%q\n' "${AUX_ENDPOINT_TIMEOUT_S:-}"
  printf 'export AUX_ENDPOINT_MAX_TOKENS=%q\n' "${AUX_ENDPOINT_MAX_TOKENS:-}"
  printf 'export AUX_ENDPOINT_TEMPERATURE=%q\n' "${AUX_ENDPOINT_TEMPERATURE:-}"
  printf 'export AUX_ENDPOINT_TOP_P=%q\n' "${AUX_ENDPOINT_TOP_P:-}"
  printf 'export AUX_ENDPOINT_ENABLE_THINKING=%q\n' "${AUX_ENDPOINT_ENABLE_THINKING:-}"
  printf 'export AUX_ENDPOINT_SEPARATE_REASONING=%q\n' "${AUX_ENDPOINT_SEPARATE_REASONING:-}"
  printf 'export AUX_ENDPOINT_REASONING_EFFORT=%q\n' "${AUX_ENDPOINT_REASONING_EFFORT:-}"
}

start_env_server() {
  require_runtime
  local config="${ENV_CONFIG:?Set ENV_CONFIG}"
  [ -f "${config}" ] || { echo "Missing env config: ${config}" >&2; exit 1; }
  local script runtime_env
  runtime_env=$(server_runtime_exports)
  case "${ENV_NAME}" in
    webshop)
      script=$(printf 'cd %q\n%s\nexport PYTHONNOUSERSITE=1 WEBSHOP_LIB=%q JAVA_HOME=%q JVM_PATH=%q PYTHONPATH=%q\n%q examples/agent_env/webshop/server.py --host 0.0.0.0 --port %q --config %q\n' \
        "${REPO_DIR}" "${runtime_env}" "${MLF_LOCAL_ROOT}/code/WebShop" "${MLF_LOCAL_ENVS}/webshop/lib/jvm" "${MLF_LOCAL_ENVS}/webshop/lib/jvm/lib/server/libjvm.so" "${REPO_DIR}:${MLF_LOCAL_ROOT}/code/WebShop" "${MLF_LOCAL_ENVS}/webshop/bin/python" "${ENV_PORT}" "${config}")
      ;;
    alfworld)
      script=$(printf 'cd %q\n%s\nexport PYTHONNOUSERSITE=1 PYTHONPATH=%q\n%q examples/agent_env/alfworld/server.py --host 0.0.0.0 --port %q --config %q\n' \
        "${REPO_DIR}" "${runtime_env}" "${REPO_DIR}" "${MLF_LOCAL_ENVS}/alfworld/bin/python" "${ENV_PORT}" "${config}")
      ;;
    tau2)
      script=$(printf 'cd %q\n%s\nexport PYTHONNOUSERSITE=1 LITELLM_LOCAL_MODEL_COST_MAP=True PYTHONPATH=%q\n%q examples/agent_env/tau2/server.py --host 0.0.0.0 --port %q --config %q\n' \
        "${REPO_DIR}" "${runtime_env}" "${REPO_DIR}" "${MLF_LOCAL_ENVS}/tau2/bin/python" "${ENV_PORT}" "${config}")
      ;;
    appworld)
      script=$(printf 'cd %q\n%s\nexport PYTHONNOUSERSITE=1 HOME=%q PYTHONPATH=%q\n%q examples/agent_env/appworld/server.py --host 0.0.0.0 --port %q --config %q\n' \
        "${REPO_DIR}" "${runtime_env}" "${MLF_LOCAL_ROOT}/data/appworld" "${REPO_DIR}" "${MLF_LOCAL_ENVS}/appworld/bin/python" "${ENV_PORT}" "${config}")
      ;;
  esac
  tmux_start_local "mlf_${ENV_NAME}_env" "${script}" "$(role_log_path "${ENV_NAME}_env_server.log")"
}

start_ray_head() {
  local node_ip=${HEAD_ADDRESS:-}
  [ -n "${node_ip}" ] || node_ip=$(hostname -I | tr ' ' '\n' | grep -m1 .)
  local script attempt
  script=$(printf 'export PYTHONNOUSERSITE=1 RAY_DISABLE_DOCKER_CPU_WARNING=1\n[ ! -f %q ] || { set -a; source %q; set +a; }\nexport CUDA_VISIBLE_DEVICES=%q\nmkdir -p %q\n%q -m ray.scripts.scripts start --head --node-ip-address %q --port %q --num-gpus %q --min-worker-port %q --max-worker-port %q --disable-usage-stats --dashboard-host=0.0.0.0 --dashboard-port=8265 --block\n' \
    "${WANDB_SECRET_FILE}" "${WANDB_SECRET_FILE}" "${RAY_CUDA_VISIBLE_DEVICES}" "${LOG_DIR}" "${SLIME_PYTHON}" "${node_ip}" "${RAY_PORT}" "${NUM_GPUS_PER_NODE_FOR_RAY}" "${RAY_MIN_WORKER_PORT}" "${RAY_MAX_WORKER_PORT}")
  for attempt in $(seq 1 "${RAY_START_MAX_ATTEMPTS}"); do
    echo "Starting Ray head attempt ${attempt}/${RAY_START_MAX_ATTEMPTS}"
    [ "${DRY_RUN}" = "1" ] || "${SLIME_PYTHON}" -m ray.scripts.scripts stop --force || true
    tmux_start_local mlf_ray_head "${script}" "${LOG_DIR}/ray_head.log"
    if wait_ray_head_ready; then
      return 0
    fi
    tmux kill-session -t mlf_ray_head 2>/dev/null || true
    sleep 5
  done
  echo "Ray head failed after ${RAY_START_MAX_ATTEMPTS} attempts" >&2
  return 1
}

start_ray_worker() {
  local head_addr=$1
  local node_ip
  node_ip=$(hostname -I | tr ' ' '\n' | grep -m1 .)
  [ "${DRY_RUN}" = "1" ] || "${SLIME_PYTHON}" -m ray.scripts.scripts stop --force || true
  local script
  script=$(printf 'export PYTHONNOUSERSITE=1 RAY_DISABLE_DOCKER_CPU_WARNING=1\n[ ! -f %q ] || { set -a; source %q; set +a; }\nexport CUDA_VISIBLE_DEVICES=%q\nmkdir -p %q\n%q -m ray.scripts.scripts start --address %q --node-ip-address %q --num-gpus %q --min-worker-port %q --max-worker-port %q --disable-usage-stats --block\n' \
    "${WANDB_SECRET_FILE}" "${WANDB_SECRET_FILE}" "${RAY_CUDA_VISIBLE_DEVICES}" "${LOG_DIR}" "${SLIME_PYTHON}" "${head_addr}:${RAY_PORT}" "${node_ip}" "${NUM_GPUS_PER_NODE_FOR_RAY}" "${RAY_MIN_WORKER_PORT}" "${RAY_MAX_WORKER_PORT}")
  tmux_start_local mlf_ray_worker "${script}" "$(role_log_path "ray_worker.log")"
}

wait_http() {
  local url=$1
  local py=${SLIME_PYTHON}
  if [ "${DRY_RUN}" = "1" ]; then
    echo "+ wait_http ${url}"
    return 0
  fi
  for _ in $(seq 1 300); do
    if "${py}" - <<PY 2>/dev/null
import json, urllib.request
data = json.loads(urllib.request.urlopen("${url}", timeout=2).read().decode())
raise SystemExit(0 if data.get("ok") else 1)
PY
    then
      echo "ready: ${url}"
      return 0
    fi
    sleep 2
  done
  echo "Timed out waiting for ${url}" >&2
  return 1
}

remote_wait_http() {
  local host=$1
  local url=$2
  local cmd
  cmd=$(cat <<EOF
${SLIME_PYTHON@Q} - <<'PY'
import json, urllib.request, time, sys
url = ${url@Q}
for _ in range(300):
    try:
        data = json.loads(urllib.request.urlopen(url, timeout=2).read().decode())
        if data.get("ok"):
            print("ready", url)
            sys.exit(0)
    except Exception:
        pass
    time.sleep(2)
sys.exit(1)
PY
EOF
)
  echo "Waiting ${host} ${url}"
  remote_query "${host}" "${cmd}"
}

ray_alive_nodes() {
  timeout 20 "${SLIME_PYTHON}" - <<PY
import ray
try:
    ray.init(address="127.0.0.1:${RAY_PORT}", ignore_reinit_error=True, logging_level="ERROR")
    print(sum(1 for n in ray.nodes() if n.get("Alive")))
finally:
    ray.shutdown()
PY
}

wait_ray_head_ready() {
  local deadline=$((SECONDS + RAY_HEAD_START_TIMEOUT_S))
  local alive
  if [ "${DRY_RUN}" = "1" ]; then
    echo "+ wait_ray_head_ready"
    return 0
  fi
  while [ "${SECONDS}" -lt "${deadline}" ]; do
    alive=$(ray_alive_nodes 2>/dev/null | tail -n 1 || true)
    if [ "${alive:-0}" -ge 1 ] 2>/dev/null; then
      echo "Ray head ready: alive=${alive}"
      return 0
    fi
    if ! tmux_session_active mlf_ray_head; then
      echo "Ray head tmux exited before ready" >&2
      tail -n 80 "${LOG_DIR}/ray_head.log" >&2 || true
      return 1
    fi
    sleep 2
  done
  echo "Timed out waiting for Ray head" >&2
  tail -n 80 "${LOG_DIR}/ray_head.log" >&2 || true
  return 1
}

wait_ray_nodes() {
  local expected=$1
  local alive
  if [ "${DRY_RUN}" = "1" ]; then
    echo "+ wait_ray_nodes ${expected}"
    return 0
  fi
  for _ in $(seq 1 180); do
    alive=$(ray_alive_nodes 2>/dev/null | tail -n 1 || true)
    if [ "${alive:-0}" -ge "${expected}" ] 2>/dev/null; then
      echo "Ray ready: alive=${alive}"
      return 0
    fi
    echo "Ray not ready: alive=${alive:-unknown}/${expected}"
    sleep 5
  done
  echo "Timed out waiting for Ray nodes" >&2
  return 1
}

start_router() {
  local workers_csv=$1
  local script
  script=$(printf 'cd %q\nexport PYTHONNOUSERSITE=1\nmkdir -p %q\n%q examples/agent_env/router.py --host 0.0.0.0 --port %q --workers %q\n' \
    "${REPO_DIR}" "${LOG_DIR}" "${SLIME_PYTHON}" "${ROUTER_PORT}" "${workers_csv}")
  tmux_start_local "mlf_${ENV_NAME}_router" "${script}" "${LOG_DIR}/${ENV_NAME}_router.log"
}

write_train_driver() {
  local router_url=$1
  local driver="${LOG_DIR}/${ENV_NAME}_train_driver.sh"
  {
    printf '#!/usr/bin/env bash\nset -euo pipefail\n'
    printf 'export AGENT_ENV_ROUTER_URL=%q\n' "${router_url}"
    printf 'export WEBSHOP_ENV_SERVER_URL=%q\n' "${router_url}"
    printf 'export ALFWORLD_ENV_SERVER_URL=%q\n' "${router_url}"
    printf 'export TAU2_ENV_SERVER_URL=%q\n' "${router_url}"
    printf 'export APPWORLD_ENV_SERVER_URL=%q\n' "${router_url}"
    printf 'export MLF_NAS_ROOT=%q\n' "${MLF_NAS_ROOT}"
    printf 'export MLF_LOCAL_ROOT=%q\n' "${MLF_LOCAL_ROOT}"
    printf 'export MLF_LOCAL_ENVS=%q\n' "${MLF_LOCAL_ENVS}"
    printf 'export REPO_DIR=%q\n' "${REPO_DIR}"
    printf 'export ENV_CONFIG=%q\n' "${ENV_CONFIG}"
    printf 'export TRAIN_PROFILE=%q\n' "${RESOLVED_TRAIN_PROFILE}"
    printf 'export CUSTOM_CONFIG_PATH=%q\n' "${ENV_CONFIG}"
    printf 'export SLIME_ENV=%q\n' "${SLIME_ENV}"
    printf 'export CUDA_VISIBLE_DEVICES=%q\n' "${RAY_CUDA_VISIBLE_DEVICES}"
    printf 'export RAY_CUDA_VISIBLE_DEVICES=%q\n' "${RAY_CUDA_VISIBLE_DEVICES}"
    printf 'export RUN_ROOT=%q\n' "${RUN_ROOT}"
    printf 'export LOG_DIR=%q\n' "${LOG_DIR}"
    printf 'export WANDB_DIR=%q\n' "${WANDB_DIR}"
    printf 'export SAVE_DIR=%q\n' "${SAVE_DIR}"
    printf 'export AUX_ENV_FILE=%q\n' "${AUX_ENV_FILE:-}"
    printf 'if [ -n "${AUX_ENV_FILE:-}" ] && [ -f "${AUX_ENV_FILE}" ]; then\n'
    printf '  set -a\n'
    printf '  source "${AUX_ENV_FILE}"\n'
    printf '  set +a\n'
    printf 'fi\n'
    printf 'cd %q\n' "${REPO_DIR}"
    printf 'bash %q\n' "${TRAIN_ADAPTER}"
  } > "${driver}"
  chmod +x "${driver}"
  printf '%s\n' "${driver}"
}

start_train_driver() {
  local router_url=$1
  local driver status_file train_log wrapper bench_log
  driver=$(write_train_driver "${router_url}")
  status_file="${LOG_DIR}/${ENV_NAME}_train_status.env"
  train_log="${LOG_DIR}/${ENV_NAME}_train.log"
  wrapper="${LOG_DIR}/${ENV_NAME}_train_tmux.sh"
  bench_log="${LOG_DIR}/bench_on_train_exit.log"
  {
    printf '#!/usr/bin/env bash\nset +e\n'
    printf 'DRIVER=%q\n' "${driver}"
    printf 'TRAIN_LOG=%q\n' "${train_log}"
    printf 'STATUS_FILE=%q\n' "${status_file}"
    printf 'BENCH_LOG=%q\n' "${bench_log}"
    printf 'BENCH_ON_TRAIN_EXIT=%q\n' "${BENCH_ON_TRAIN_EXIT}"
    printf 'MLF_NAS_ROOT=%q\n' "${MLF_NAS_ROOT}"
    printf 'RUN_BENCH=%q\n' "${MLF_NAS_ROOT}/bash/run_bench.sh"
    printf 'NODES_FILE=%q\n' "${NODES_FILE}"
    printf 'NODE_INDICES=%q\n' "${NODE_INDICES}"
    printf 'SSH_USER=%q\n' "${SSH_USER}"
    printf 'SSH_PORT=%q\n' "${SSH_PORT}"
    printf 'SSH_KEY=%q\n' "${SSH_KEY}"
    printf 'SSH_IPV6=%q\n' "${SSH_IPV6}"
    printf 'SSH_JUMP=%q\n' "${SSH_JUMP}"
    printf 'BENCH_ON_EXIT_SUPPRESS_FILE=%q\n' "${BENCH_ON_EXIT_SUPPRESS_FILE}"
    cat <<'EOF'
finish() {
  local code=$?
  local now suppress_until skip_bench=0
  printf "exit_code=%s\nend_time=%s\n" "${code}" "$(date -Is)" > "${STATUS_FILE}"
  if [ -n "${BENCH_ON_EXIT_SUPPRESS_FILE}" ] && [ -f "${BENCH_ON_EXIT_SUPPRESS_FILE}" ]; then
    now=$(date +%s)
    suppress_until=$(cat "${BENCH_ON_EXIT_SUPPRESS_FILE}" 2>/dev/null || echo 0)
    if [ "${suppress_until:-0}" -gt "${now}" ] 2>/dev/null; then
      skip_bench=1
      printf "[%s] train exited code=%s; skip run_bench because reset suppression is active until %s\n" \
        "$(date -Is)" "${code}" "${suppress_until}" >> "${BENCH_LOG}" 2>&1 || true
    fi
  fi
  if [ "${BENCH_ON_TRAIN_EXIT}" = "1" ] && [ "${skip_bench}" != "1" ] && [ -n "${NODES_FILE}" ] && [ -f "${RUN_BENCH}" ]; then
    {
      echo "[$(date -Is)] train exited code=${code}; running run_bench start --nodes ${NODES_FILE} --node ${NODE_INDICES}"
      bench_args=(start --nodes "${NODES_FILE}")
      [ -z "${NODE_INDICES}" ] || bench_args+=(--node "${NODE_INDICES}")
      MLF_NAS_ROOT="${MLF_NAS_ROOT}" SSH_USER="${SSH_USER}" SSH_PORT="${SSH_PORT}" \
        SSH_KEY="${SSH_KEY}" SSH_IPV6="${SSH_IPV6}" SSH_JUMP="${SSH_JUMP}" \
        bash "${RUN_BENCH}" "${bench_args[@]}"
    } >> "${BENCH_LOG}" 2>&1 || true
  fi
  exit "${code}"
}

trap finish EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

printf "state=running\nstart_time=%s\n" "$(date -Is)" > "${STATUS_FILE}"
bash "${DRIVER}" > "${TRAIN_LOG}" 2>&1
EOF
    printf 'code=$?\n'
    printf 'exit "$code"\n'
  } > "${wrapper}"
  chmod +x "${wrapper}"
  tmux_start_local "mlf_${ENV_NAME}_train" "bash ${wrapper}"
  echo "Training submitted in tmux: mlf_${ENV_NAME}_train"
  echo "Training log: ${train_log}"
  echo "Train status: ${status_file}"
}

run_worker() {
  source_env_file "${RESOLVED_CONFIG}" resolved
  start_env_server
  wait_http "http://127.0.0.1:${ENV_PORT}/health"
  start_ray_worker "${HEAD_ADDRESS:?worker needs --head-address}"
}

run_head() {
  source_env_file "${RESOLVED_CONFIG}" resolved
  mkdir -p "${LOG_DIR}"
  HEAD_ORCHESTRATION_COMPLETE=0
  head_failure_guard() {
    local code=$?
    if [ "${code}" -ne 0 ] \
      && [ "${HEAD_ORCHESTRATION_COMPLETE}" != "1" ] \
      && [ "${BENCH_ON_LAUNCH_FAILURE}" = "1" ]; then
      echo "Head orchestration failed with exit_code=${code}; starting bench on ${NODES_FILE}" >&2
      run_bench_nodes start "${NODES_FILE}" "${NODE_INDICES}"
    fi
    exit "${code}"
  }
  trap head_failure_guard EXIT
  local head_addr=${HEAD_ADDRESS:-}
  [ -n "${head_addr}" ] || head_addr=$(hostname -I | tr ' ' '\n' | grep -m1 .)
  local head_http="http://$(http_host "${head_addr}"):${ENV_PORT}"
  local env_urls=("${head_http}")
  start_ray_head
  start_env_server
  wait_http "http://127.0.0.1:${ENV_PORT}/health"

  local node node_addr worker_script
  for node in $(read_nodes | tail -n +2); do
    if [ "${DRY_RUN}" = "1" ]; then
      node_addr="${node}"
    else
      node_addr=$(remote_first_ip "${node}")
    fi
    env_urls+=("http://$(http_host "${node_addr}"):${ENV_PORT}")
    worker_script=$(printf 'cd %q\nMLF_NAS_ROOT=%q MLF_LOCAL_ENVS=%q MLF_LOCAL_ROOT=%q SLIME_ENV=%q SSH_KEY=%q SSH_IPV6=%q bash scripts/utils/launch_agentic_training.sh --internal-role worker --resolved %q --head-address %q\n' \
      "${REPO_DIR}" "${MLF_NAS_ROOT}" "${MLF_LOCAL_ENVS}" "${MLF_LOCAL_ROOT}" "${SLIME_ENV}" "${SSH_KEY}" "${SSH_IPV6}" "${RESOLVED_CONFIG}" "${head_addr}")
    tmux_start_remote "${node}" mlf_multi_worker "${worker_script}" "${LOG_DIR}/multi_worker_$(safe_label "${node}").log"
  done
  for node in $(read_nodes | tail -n +2); do
    remote_wait_http "${node}" "http://127.0.0.1:${ENV_PORT}/health"
  done
  wait_ray_nodes "$(node_count)"

  local workers_csv
  workers_csv=$(IFS=,; echo "${env_urls[*]}")
  start_router "${workers_csv}"
  wait_http "http://127.0.0.1:${ROUTER_PORT}/health"
  start_train_driver "http://$(http_host "${head_addr}"):${ROUTER_PORT}"
  HEAD_ORCHESTRATION_COMPLETE=1
  trap - EXIT
}

write_resolved_launch_config() {
  load_aux_endpoint_env
  write_named_env "${RESOLVED_LAUNCH_CONFIG}" \
    MLF_NAS_ROOT REPO_DIR MLF_LOCAL_ENVS MLF_LOCAL_ROOT WANDB_SECRET_FILE SLIME_ENV SLIME_PYTHON \
    ENV_NAME ENV_CONFIG MODEL_PROFILE TRAIN_PROFILE TRAIN_ADAPTER RESOLVED_TRAIN_PROFILE \
    NODES_FILE NODE_INDICES AUX_NODES_FILE AUX_NODE_INDICES AUX_ENV_FILE ENV_PORT ROUTER_PORT RAY_PORT \
    RAY_CUDA_VISIBLE_DEVICES NUM_GPUS_PER_NODE_FOR_RAY RAY_MIN_WORKER_PORT RAY_MAX_WORKER_PORT \
    RAY_START_MAX_ATTEMPTS RAY_HEAD_START_TIMEOUT_S \
    RUN_ROOT LOG_DIR WANDB_DIR SAVE_DIR EXP_PROJECT EXP_NAME \
    RESET_TRAIN_RUNTIME_ON_START BENCH_ON_TRAIN_EXIT BENCH_ON_LAUNCH_FAILURE BENCH_ON_EXIT_SUPPRESS_FILE \
    SSH_USER SSH_PORT SSH_KEY SSH_IPV6 SSH_JUMP \
    AUX_ENDPOINT_PROVIDER AUX_ENDPOINT_MODEL AUX_ENDPOINT_BASE_URL AUX_ENDPOINT_API_KEY_PATH \
    AUX_ENDPOINT_TIMEOUT_S AUX_ENDPOINT_MAX_TOKENS AUX_ENDPOINT_TEMPERATURE AUX_ENDPOINT_TOP_P \
    AUX_ENDPOINT_ENABLE_THINKING AUX_ENDPOINT_SEPARATE_REASONING AUX_ENDPOINT_REASONING_EFFORT \
    AUX_ENDPOINT_STARTED_LOCAL AUX_ENDPOINT_NODES_FILE AUX_ENDPOINT_SESSION
  # RESOLVED_CONFIG is used by internal roles; keep it self-referential.
  printf 'RESOLVED_CONFIG=%q\n' "${RESOLVED_LAUNCH_CONFIG}" >> "${RESOLVED_LAUNCH_CONFIG}"
}

prepare_run() {
  [ -n "${RUN_PROFILE}" ] || { echo "Missing run profile" >&2; usage >&2; exit 1; }
  local run_profile_path topology_path model_path train_path aux_path
  run_profile_path=$(resolve_path "${RUN_PROFILE}")
  source_env_file "${run_profile_path}" run
  topology_path=$(resolve_path "${TOPOLOGY_PROFILE:?Set TOPOLOGY_PROFILE in run profile}")
  source_env_file "${topology_path}" topology
  model_path=$(resolve_path "${MODEL_PROFILE:?Set MODEL_PROFILE in run profile}")
  source_env_file "${model_path}" model
  train_path=$(resolve_path "${TRAIN_PROFILE:?Set TRAIN_PROFILE in run profile}")
  source_env_file "${train_path}" train

  ENV_NAME=${ENV_NAME:?Set ENV_NAME in run profile}
  ENV_CONFIG=$(resolve_path "${ENV_CONFIG:-examples/agent_env/${ENV_NAME}/env_config.yaml}")
  TRAIN_ADAPTER=$(resolve_path "${TRAIN_ADAPTER}")
  NODES_FILE=$(resolve_path "${NODES_FILE}")
  [ -z "${AUX_NODES_FILE}" ] || AUX_NODES_FILE=$(resolve_path "${AUX_NODES_FILE}")
  [ -z "${NODES_FILE}" ] || [ -f "${NODES_FILE}" ] || { echo "Missing nodes file: ${NODES_FILE}" >&2; exit 1; }
  if [ "$(node_count)" -eq 0 ]; then
    echo "No training nodes selected from ${NODES_FILE} with NODE_INDICES=${NODE_INDICES}" >&2
    exit 1
  fi
  ENV_PORT=${ENV_PORT:-18180}
  ROUTER_PORT=${ROUTER_PORT:-19000}
  RAY_CUDA_VISIBLE_DEVICES=${RAY_CUDA_VISIBLE_DEVICES:-${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}}
  NUM_GPUS_PER_NODE_FOR_RAY=${NUM_GPUS_PER_NODE_FOR_RAY:-8}
  RAY_MIN_WORKER_PORT=${RAY_MIN_WORKER_PORT:-20000}
  RAY_MAX_WORKER_PORT=${RAY_MAX_WORKER_PORT:-29999}
  EXP_PROJECT=${EXP_PROJECT:-${PROJECT_NAME:-${MODEL_BASENAME:-model}_${ENV_NAME}_grpo}}
  EXP_NAME=${EXP_NAME:-${RUN_NAME:-${MODEL_BASENAME:-model}-${ENV_NAME}-grpo}}
  RUN_ROOT=${RUN_ROOT:-${MLF_NAS_ROOT}/runs/${EXP_PROJECT}/${EXP_NAME}}
  LOG_DIR=${LOG_DIR:-${RUN_ROOT}/logs}
  WANDB_DIR=${WANDB_DIR:-${RUN_ROOT}/wandb}
  SAVE_DIR=${SAVE_DIR:-${RUN_ROOT}/checkpoints}
  AUX_ENV_FILE=${AUX_ENV_FILE:-${LOG_DIR}/aux_endpoint.env}
  RESOLVED_TRAIN_PROFILE=${LOG_DIR}/resolved_train_profile.env
  RESOLVED_LAUNCH_CONFIG=${LOG_DIR}/resolved_launch.env
  mkdir -p "${LOG_DIR}" "${WANDB_DIR}" "${SAVE_DIR}"

  write_resolved_profile "${RESOLVED_TRAIN_PROFILE}" "${run_profile_path}" "${topology_path}" "${model_path}" "${train_path}"
  {
    printf '\n'
    quote_exports MLF_NAS_ROOT MLF_LOCAL_ROOT MLF_LOCAL_ENVS REPO_DIR TRAIN_ADAPTER \
      RUN_ROOT LOG_DIR WANDB_DIR SAVE_DIR
  } >> "${RESOLVED_TRAIN_PROFILE}"

  if [ -n "${AUX_PROFILE:-}" ]; then
    aux_path=$(resolve_path "${AUX_PROFILE}")
    source_env_file "${aux_path}" aux
    RESOLVED_AUX_PROFILE=${LOG_DIR}/resolved_aux_profile.env
    write_resolved_profile "${RESOLVED_AUX_PROFILE}" "${aux_path}"
    {
      printf '\n'
      quote_exports MLF_NAS_ROOT MLF_LOCAL_ENVS REPO_DIR LOG_DIR AUX_ENV_FILE AUX_NODES_FILE AUX_NODE_INDICES
    } >> "${RESOLVED_AUX_PROFILE}"
  else
    RESOLVED_AUX_PROFILE=
  fi
}

start_aux_endpoint() {
  [ -n "${RESOLVED_AUX_PROFILE:-}" ] || return 0
  local aux_nodes_arg=()
  local aux_index_arg=()
  [ -z "${AUX_NODES_FILE:-}" ] || aux_nodes_arg=(--nodes "${AUX_NODES_FILE}")
  [ -z "${AUX_NODE_INDICES:-}" ] || aux_index_arg=(--node-index "${AUX_NODE_INDICES}")
  run_bench_nodes stop "${AUX_NODES_FILE:-}" "${AUX_NODE_INDICES:-}"
  local dry=()
  [ "${DRY_RUN}" = "0" ] || dry=(--dry-run)
  bash "${REPO_DIR}/scripts/utils/aux_endpoint.sh" start \
    --config "${RESOLVED_AUX_PROFILE}" \
    --env-file "${AUX_ENV_FILE}" \
    "${aux_nodes_arg[@]}" \
    "${aux_index_arg[@]}" \
    "${dry[@]}"
}

submit_head() {
  local head head_addr script
  head=$(first_node)
  if [ "${DRY_RUN}" = "1" ]; then
    head_addr="${head}"
  else
    head_addr=$(remote_first_ip "${head}")
  fi
  script=$(printf 'cd %q\nMLF_NAS_ROOT=%q MLF_LOCAL_ENVS=%q MLF_LOCAL_ROOT=%q SLIME_ENV=%q SSH_KEY=%q SSH_IPV6=%q SSH_JUMP= bash scripts/utils/launch_agentic_training.sh --internal-role head --resolved %q --head-address %q\n' \
    "${REPO_DIR}" "${MLF_NAS_ROOT}" "${MLF_LOCAL_ENVS}" "${MLF_LOCAL_ROOT}" "${SLIME_ENV}" "${SSH_KEY}" "${SSH_IPV6}" "${RESOLVED_LAUNCH_CONFIG}" "${head_addr}")
  if is_current_node "${head}"; then
    RESOLVED_CONFIG="${RESOLVED_LAUNCH_CONFIG}" HEAD_ADDRESS="${head_addr}" run_head
  else
    tmux_start_remote "${head}" mlf_multi_head "${script}" "${LOG_DIR}/multi_head.log"
    echo "Head orchestration submitted."
    echo "Head log: ${head}:${LOG_DIR}/multi_head.log"
  fi
}

LAUNCH_BENCH_GUARD_ACTIVE=0
LAUNCH_COMPLETED=0
HEAD_ORCHESTRATION_COMPLETE=0

bench_on_launch_exit() {
  local code=$?
  if [ "${code}" -ne 0 ] \
    && [ "${LAUNCH_BENCH_GUARD_ACTIVE}" = "1" ] \
    && [ "${LAUNCH_COMPLETED}" != "1" ] \
    && [ "${BENCH_ON_LAUNCH_FAILURE}" = "1" ]; then
    echo "Launch failed with exit_code=${code}; starting bench on ${NODES_FILE}" >&2
    run_bench_nodes start "${NODES_FILE}" "${NODE_INDICES}"
  fi
  exit "${code}"
}

stop_bench_nodes_quiescent() {
  run_bench_nodes stop "${NODES_FILE}" "${NODE_INDICES}"
  if [ "${DRY_RUN}" != "1" ]; then
    sleep 20
  fi
  run_bench_nodes stop "${NODES_FILE}" "${NODE_INDICES}"
}

main_launch() {
  prepare_run
  LAUNCH_BENCH_GUARD_ACTIVE=1
  LAUNCH_COMPLETED=0
  trap bench_on_launch_exit EXIT
  start_aux_endpoint
  write_resolved_launch_config
  reset_runtime_on_nodes
  stop_bench_nodes_quiescent
  submit_head
  run_bench_nodes stop "${NODES_FILE}" "${NODE_INDICES}"
  LAUNCH_COMPLETED=1
  LAUNCH_BENCH_GUARD_ACTIVE=0
  trap - EXIT
}

case "${INTERNAL_ROLE}" in
  "")
    main_launch
    ;;
  head)
    [ -n "${RESOLVED_CONFIG}" ] || { echo "--resolved is required for internal head" >&2; exit 1; }
    run_head
    ;;
  worker)
    [ -n "${RESOLVED_CONFIG}" ] || { echo "--resolved is required for internal worker" >&2; exit 1; }
    run_worker
    ;;
  *)
    echo "Unknown internal role: ${INTERNAL_ROLE}" >&2
    exit 1
    ;;
esac
