#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

MLF_NAS_ROOT=${MLF_NAS_ROOT:-/mnt/bn/jixf-nas-lq/mlf}
MLF_LOCAL_ROOT=${MLF_LOCAL_ROOT:-/tmp/mlf-runtime}
MLF_LOCAL_ENVS=${MLF_LOCAL_ENVS:-/tmp/mlf-envs}
SLIME_ENV=${SLIME_ENV:-${MLF_LOCAL_ENVS}/slime}
RUN_PROFILE=${RUN_PROFILE:-}
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage: launch_agent_env.sh <run-profile.env> [--dry-run]

The run profile selects env, topology, train, and optional aux profiles. The
launcher materializes resolved profiles into the run log directory before
starting aux and training infrastructure.
EOF
}

if [ $# -gt 0 ] && [[ "${1}" != -* ]]; then
  RUN_PROFILE=$1
  shift
fi

EXTRA_LAUNCH_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=1; EXTRA_LAUNCH_ARGS+=(--dry-run); shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

[ -n "${RUN_PROFILE}" ] || { usage >&2; exit 2; }

resolve_repo_path() {
  local path=$1
  if [[ "${path}" = /* ]]; then
    printf '%s\n' "${path}"
  else
    printf '%s/%s\n' "${REPO_DIR}" "${path}"
  fi
}

source_profile() {
  local path=$1
  local label=$2
  [ -n "${path}" ] || return 0
  path=$(resolve_repo_path "${path}")
  [ -f "${path}" ] || { echo "Missing ${label} profile: ${path}" >&2; exit 1; }
  set -a
  # shellcheck disable=SC1090
  source "${path}"
  set +a
  LOADED_PROFILE_PATHS+=("${path}")
}

profile_keys() {
  local path
  for path in "$@"; do
    [ -n "${path}" ] && [ -f "${path}" ] || continue
    sed -nE 's/^([A-Za-z_][A-Za-z0-9_]*)=.*/\1/p' "${path}"
  done
}

write_resolved_profile() {
  local target=$1
  shift
  local extra_keys=("$@")
  mkdir -p "$(dirname "${target}")"
  {
    printf '# Generated by %s\n' "$(basename "$0")"
    printf '# Run profile: %s\n' "${RUN_PROFILE_PATH}"
    {
      profile_keys "${LOADED_PROFILE_PATHS[@]}"
      printf '%s\n' "${extra_keys[@]}"
    } | awk 'NF && !seen[$0]++' | while read -r key; do
      printf '%s=%q\n' "${key}" "${!key-}"
    done
  } > "${target}"
  printf '%s\n' "${target}"
}

LOADED_PROFILE_PATHS=()
RUN_PROFILE_PATH=$(resolve_repo_path "${RUN_PROFILE}")
source_profile "${RUN_PROFILE_PATH}" run

if [ -n "${TOPOLOGY_PROFILE:-}" ]; then
  source_profile "${TOPOLOGY_PROFILE}" topology
fi
if [ -n "${TRAIN_PROFILE:-}" ]; then
  source_profile "${TRAIN_PROFILE}" train
fi

ENV_NAME=${ENV_NAME:?Set ENV_NAME in run profile}
ENV_RUN_SCRIPT=${ENV_RUN_SCRIPT:?Set ENV_RUN_SCRIPT in run profile}
ENV_CONFIG=${ENV_CONFIG:-examples/agent_env/${ENV_NAME}/train_config.yaml}
NODES_FILE=${NODES_FILE:-}
ENV_PORT=${ENV_PORT:-18180}
ROUTER_PORT=${ROUTER_PORT:-19000}
RAY_CUDA_VISIBLE_DEVICES=${RAY_CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}
NUM_GPUS_PER_NODE_FOR_RAY=${NUM_GPUS_PER_NODE_FOR_RAY:-8}

EXP_PROJECT=${EXP_PROJECT:-${PROJECT_NAME:-${MODEL_BASENAME:-model}_${ENV_NAME}_grpo}}
EXP_NAME=${EXP_NAME:-${RUN_NAME:-${MODEL_BASENAME:-model}-${ENV_NAME}-grpo}}
RUN_ROOT=${RUN_ROOT:-${MLF_NAS_ROOT}/runs/${EXP_PROJECT}/${EXP_NAME}}
LOG_DIR=${LOG_DIR:-${RUN_ROOT}/logs}
WANDB_DIR=${WANDB_DIR:-${RUN_ROOT}/wandb}
SAVE_DIR=${SAVE_DIR:-${RUN_ROOT}/checkpoints}
AUX_ENV_FILE=${AUX_ENV_FILE:-${LOG_DIR}/aux_endpoint.env}

ENV_RUN_SCRIPT_PATH=$(resolve_repo_path "${ENV_RUN_SCRIPT}")
[ -f "${ENV_RUN_SCRIPT_PATH}" ] || { echo "Missing env run script: ${ENV_RUN_SCRIPT_PATH}" >&2; exit 1; }
ENV_CONFIG_PATH=$(resolve_repo_path "${ENV_CONFIG}")
[ -f "${ENV_CONFIG_PATH}" ] || { echo "Missing env config: ${ENV_CONFIG_PATH}" >&2; exit 1; }
if [ -n "${NODES_FILE}" ]; then
  NODES_FILE_PATH=$(resolve_repo_path "${NODES_FILE}")
  [ -f "${NODES_FILE_PATH}" ] || { echo "Missing nodes file: ${NODES_FILE_PATH}" >&2; exit 1; }
fi

export RAY_CUDA_VISIBLE_DEVICES NUM_GPUS_PER_NODE_FOR_RAY LOG_DIR AUX_ENV_FILE

RESOLVED_TRAIN_PROFILE=$(write_resolved_profile \
  "${LOG_DIR}/resolved_train_profile.env" \
  MLF_NAS_ROOT MLF_LOCAL_ROOT MLF_LOCAL_ENVS REPO_DIR ENV_NAME ENV_CONFIG \
  RUN_ROOT LOG_DIR WANDB_DIR SAVE_DIR EXP_PROJECT EXP_NAME)

if [ -n "${AUX_PROFILE:-}" ]; then
  AUX_PROFILE_PATH=$(resolve_repo_path "${AUX_PROFILE}")
  [ -f "${AUX_PROFILE_PATH}" ] || { echo "Missing aux profile: ${AUX_PROFILE_PATH}" >&2; exit 1; }
  AUX_LOADED_PROFILE_PATHS=("${AUX_PROFILE_PATH}")
  set -a
  # shellcheck disable=SC1090
  source "${AUX_PROFILE_PATH}"
  set +a
  OLD_LOADED_PROFILE_PATHS=("${LOADED_PROFILE_PATHS[@]}")
  LOADED_PROFILE_PATHS=("${AUX_LOADED_PROFILE_PATHS[@]}")
  RESOLVED_AUX_PROFILE=$(write_resolved_profile \
    "${LOG_DIR}/resolved_aux_profile.env" \
    MLF_NAS_ROOT MLF_LOCAL_ENVS REPO_DIR LOG_DIR AUX_ENV_FILE AUX_NODES_FILE)
  LOADED_PROFILE_PATHS=("${OLD_LOADED_PROFILE_PATHS[@]}")
fi

TRAIN_CMD=$(
  printf '%q ' \
    MLF_NAS_ROOT="${MLF_NAS_ROOT}" MLF_LOCAL_ROOT="${MLF_LOCAL_ROOT:-/tmp/mlf-runtime}" MLF_LOCAL_ENVS="${MLF_LOCAL_ENVS:-/tmp/mlf-envs}" \
    TRAIN_PROFILE="${RESOLVED_TRAIN_PROFILE}" \
    SLIME_ENV="${SLIME_ENV}" CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" RAY_CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" \
    RUN_ROOT="${RUN_ROOT}" LOG_DIR="${LOG_DIR}" WANDB_DIR="${WANDB_DIR}" SAVE_DIR="${SAVE_DIR}" \
    bash "${ENV_RUN_SCRIPT}"
)

cd "${REPO_DIR}"

if [ -n "${RESOLVED_AUX_PROFILE:-}" ]; then
  AUX_NODES_FILE_ARG=()
  if [ -n "${AUX_NODES_FILE:-}" ]; then
    AUX_NODES_FILE_ARG=(--nodes "$(resolve_repo_path "${AUX_NODES_FILE}")")
  fi
  bash scripts/mlf/aux_endpoint.sh start \
    --config "${RESOLVED_AUX_PROFILE}" \
    --env-file "${AUX_ENV_FILE}" \
    "${AUX_NODES_FILE_ARG[@]}" \
    "${EXTRA_LAUNCH_ARGS[@]}"
fi

LAUNCH_ARGS=(
  --env "${ENV_NAME}"
  --env-port "${ENV_PORT}"
  --router-port "${ROUTER_PORT}"
  --train-cmd "${TRAIN_CMD}"
)
if [ -n "${NODES_FILE}" ]; then
  LAUNCH_ARGS+=(--nodes "${NODES_FILE}")
fi
if [ -n "${ENV_POOL_SIZE:-}" ]; then
  LAUNCH_ARGS+=(--env-pool-size "${ENV_POOL_SIZE}")
fi
if [ -n "${DATA_SIZE:-}" ]; then
  LAUNCH_ARGS+=(--data-size "${DATA_SIZE}")
fi

ENV_CONFIG="${ENV_CONFIG}" \
bash scripts/mlf/launch_agentic_training.sh \
  "${LAUNCH_ARGS[@]}" \
  "${EXTRA_LAUNCH_ARGS[@]}"
