eval:
  defaults:
    input_key: prompt
    metadata_key: metadata
    n_samples_per_eval_prompt: 1
    max_response_len: 512
    temperature: 0.0
    top_p: 1.0
    top_k: -1
  datasets:
    - name: webshop-valid
      path: /tmp/mlf-runtime/data/webshop/valid_100.jsonl
      custom_generate_function_path: examples.webshop.generate.generate
      metadata_overrides:
        split: valid
