#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/../../../.." && pwd)"

# Infra and env setup.
NODES_FILE=${NODES_FILE:-configs/nodes/agent_env_2x8.txt}
ENV_POOL_SIZE=${ENV_POOL_SIZE:-32}
ENV_PORT=${ENV_PORT:-18180}
ROUTER_PORT=${ROUTER_PORT:-19000}
WEBSHOP_DATA_SIZE=${WEBSHOP_DATA_SIZE:-full}
RAY_CUDA_VISIBLE_DEVICES=${RAY_CUDA_VISIBLE_DEVICES:-0,1,2,3}
NUM_GPUS_PER_NODE_FOR_RAY=${NUM_GPUS_PER_NODE_FOR_RAY:-4}

# Experiment identity and persistent artifacts.
EXP_PROJECT=${EXP_PROJECT:-${PROJECT_NAME:-Qwen3-8B_webshop_grpo}}
EXP_NAME=${EXP_NAME:-${RUN_NAME:-webshop-qwen3-8b-grpo-2x8-formal-gbs128}}
RUN_ROOT=${RUN_ROOT:-/mnt/bn/jixf-nas-lq/mlf/runs/${EXP_PROJECT}/${EXP_NAME}}
LOG_DIR=${LOG_DIR:-${RUN_ROOT}/logs}
WANDB_DIR=${WANDB_DIR:-${RUN_ROOT}/wandb}
SAVE_DIR=${SAVE_DIR:-${RUN_ROOT}/checkpoints}
WANDB_PROJECT=${WANDB_PROJECT:-${EXP_PROJECT}}
WANDB_ENTITY=${WANDB_ENTITY:-yilgrimage-bytedance}
WANDB_GROUP=${WANDB_GROUP:-${EXP_NAME}}

# Slime GRPO training parameters.
TOTAL_NUM_STEPS=${TOTAL_NUM_STEPS:-100}
SAVE_INTERVAL=${SAVE_INTERVAL:-${TOTAL_NUM_STEPS}}
RESUME_FROM=${RESUME_FROM:-}
SEED=${SEED:-42}
ROLLOUT_BATCH_SIZE=${ROLLOUT_BATCH_SIZE:-16}
N_SAMPLES_PER_PROMPT=${N_SAMPLES_PER_PROMPT:-8}
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-128}
ROLLOUT_MAX_CONTEXT_LEN=${ROLLOUT_MAX_CONTEXT_LEN:-10240}
ROLLOUT_MAX_RESPONSE_LEN=${ROLLOUT_MAX_RESPONSE_LEN:-512}
MAX_TOKENS_PER_GPU=${MAX_TOKENS_PER_GPU:-20480}
SGLANG_SERVER_CONCURRENCY=${SGLANG_SERVER_CONCURRENCY:-16}
ACTOR_NUM_NODES=${ACTOR_NUM_NODES:-2}
ACTOR_GPUS=${ACTOR_GPUS:-4}
ROLLOUT_GPUS=${ROLLOUT_GPUS:-8}
NUM_GPUS=${NUM_GPUS:-4}
TP_SIZE=${TP_SIZE:-4}
CP_SIZE=${CP_SIZE:-1}
USE_KL_LOSS=${USE_KL_LOSS:-0}
KL_LOSS_COEF=${KL_LOSS_COEF:-0.00}

EXTRA_LAUNCH_ARGS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) EXTRA_LAUNCH_ARGS+=(--dry-run); shift ;;
    -h|--help) echo "Usage: $(basename "$0") [--dry-run]"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

export RAY_CUDA_VISIBLE_DEVICES NUM_GPUS_PER_NODE_FOR_RAY LOG_DIR

LOAD_ARGS=()
if [ -n "${RESUME_FROM}" ]; then
  LOAD_ARGS=(LOAD_DIR="${RESUME_FROM}")
fi

TRAIN_CMD=$(
  printf '%q ' \
    MLF_NAS_ROOT=/mnt/bn/jixf-nas-lq/mlf MLF_LOCAL_ROOT=/tmp/mlf-runtime MLF_LOCAL_ENVS=/tmp/mlf-envs \
    SLIME_ENV=/tmp/mlf-envs/slime WEBSHOP_ENV=/tmp/mlf-envs/webshop CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" RAY_CUDA_VISIBLE_DEVICES="${RAY_CUDA_VISIBLE_DEVICES}" \
    NUM_GPUS="${NUM_GPUS}" EXP_PROJECT="${EXP_PROJECT}" EXP_NAME="${EXP_NAME}" RUN_ROOT="${RUN_ROOT}" LOG_DIR="${LOG_DIR}" WANDB_DIR="${WANDB_DIR}" SAVE_DIR="${SAVE_DIR}" "${LOAD_ARGS[@]}" \
    USE_EXISTING_AGENT_INFRA=1 SUBMIT_VIA_RAY_JOB=1 ENABLE_WANDB=1 WANDB_PROJECT="${WANDB_PROJECT}" WANDB_ENTITY="${WANDB_ENTITY}" WANDB_GROUP="${WANDB_GROUP}" TRAIN_ENTRYPOINT=train_async.py \
    WEBSHOP_DATA_SIZE="${WEBSHOP_DATA_SIZE}" WEBSHOP_ENV_POOL_SIZE="${ENV_POOL_SIZE}" \
    NUM_STEPS="${TOTAL_NUM_STEPS}" NUM_ROLLOUT="${TOTAL_NUM_STEPS}" SAVE_INTERVAL="${SAVE_INTERVAL}" ROLLOUT_BATCH_SIZE="${ROLLOUT_BATCH_SIZE}" N_SAMPLES_PER_PROMPT="${N_SAMPLES_PER_PROMPT}" GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}" \
    ROLLOUT_MAX_CONTEXT_LEN="${ROLLOUT_MAX_CONTEXT_LEN}" ROLLOUT_MAX_RESPONSE_LEN="${ROLLOUT_MAX_RESPONSE_LEN}" MAX_TOKENS_PER_GPU="${MAX_TOKENS_PER_GPU}" SGLANG_SERVER_CONCURRENCY="${SGLANG_SERVER_CONCURRENCY}" \
    ACTOR_NUM_NODES="${ACTOR_NUM_NODES}" ACTOR_GPUS="${ACTOR_GPUS}" ROLLOUT_GPUS="${ROLLOUT_GPUS}" TP_SIZE="${TP_SIZE}" CP_SIZE="${CP_SIZE}" SEED="${SEED}" USE_KL_LOSS="${USE_KL_LOSS}" KL_LOSS_COEF="${KL_LOSS_COEF}" \
    bash examples/agent_env/webshop/scripts/run_qwen3_8b_webshop_grpo.sh
)

cd "${REPO_DIR}"
bash scripts/mlf/launch_agentic_training.sh \
  --env webshop \
  --nodes "${NODES_FILE}" \
  --env-pool-size "${ENV_POOL_SIZE}" \
  --env-port "${ENV_PORT}" \
  --router-port "${ROUTER_PORT}" \
  --data-size "${WEBSHOP_DATA_SIZE}" \
  --train-cmd "${TRAIN_CMD}" \
  ${EXTRA_LAUNCH_ARGS+"${EXTRA_LAUNCH_ARGS[@]}"}
